# Generated by Django 2.2 on 2019-04-09 18:20

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='newsletter/images/%Y/%m/%d', verbose_name='image'),
        ),
    ]
