# Generated by Django 2.2 on 2019-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20190409_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%D'),
        ),
    ]
