# Generated by Django 2.2 on 2019-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20190409_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
        migrations.AddField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='newsletter.Attachment'),
        ),
    ]
