# Generated by Django 2.2 on 2019-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='attachments',
        ),
        migrations.AddField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='newsletter.Attachment'),
        ),
    ]
