# Generated by Django 2.2 on 2019-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20190409_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
