# Generated by Django 2.2 on 2019-04-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20190409_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='attachment',
            new_name='attachments',
        ),
    ]
